# Generated by Django 4.2.6 on 2023-10-29 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("read_later", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
