# Generated by Django 4.2.4 on 2023-10-28 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read_later', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
