# Generated by Django 4.2.6 on 2023-10-26 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="rate",
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("komentar", models.TextField(null=True)),
                (
                    "buku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.book"
                    ),
                ),
            ],
        ),
    ]
