# Generated by Django 4.2.6 on 2023-10-29 05:35

from django.db import migrations

from django.contrib.auth.models import BaseUserManager
from django.contrib.auth.hashers import make_password
import django.contrib.auth.models as auth


def generate_superuser(apps, schema_editor):

    email = "williamsalimrjs@gmail.com"
    password = "tewkub123"

    user: auth.User = auth.User()
    user.username = "bukwet"
    user.email = BaseUserManager.normalize_email(email)
    user.password = make_password(password)
    user.is_staff = True
    user.is_superuser = True
    user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(generate_superuser),
    ]