# Generated by Django 4.2.4 on 2023-10-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20231028_0728'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchFeatureStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
