# Generated by Django 4.2.6 on 2023-10-26 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_book_publish_date_book_cover_img_book_genres_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publish_date',
        ),
    ]
