# Generated by Django 4.2.6 on 2023-10-28 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20231027_1610'),
        ('main', '0002_auto_20231028_0728'),
    ]

    operations = [
    ]
