# Generated by Django 4.2.4 on 2023-10-28 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_searchfeaturestatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchfeaturestatus',
            old_name='is_enabled',
            new_name='search_enabled',
        ),
        migrations.AddField(
            model_name='searchfeaturestatus',
            name='user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
