# Generated by Django 4.2.6 on 2023-10-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_merge_0002_auto_20231027_1610_0002_auto_20231028_0728'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteOfDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_text', models.TextField()),
                ('author', models.CharField(max_length=100)),
            ],
        ),
    ]
