# Generated by Django 4.2.4 on 2023-10-25 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_book_rate_review'),
    ]

    operations = [
    ]
