# Generated by Django 4.2.6 on 2023-10-26 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0004_alter_book_rate_alter_comment_buku_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="rate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.rate"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="buku",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.book"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
