# Generated by Django 4.2.4 on 2023-10-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20231025_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rate',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
