# Generated by Django 4.2.6 on 2023-10-28 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_auto_20231027_1159"),
        ("main", "0004_quoteofday"),
    ]

    operations = []
