# Generated by Django 4.2.4 on 2023-10-28 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_is_enabled_searchfeaturestatus_search_enabled_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchfeaturestatus',
            old_name='search_enabled',
            new_name='enabled',
        ),
        migrations.RemoveField(
            model_name='searchfeaturestatus',
            name='user',
        ),
    ]
