# Generated by Django 4.2.6 on 2023-10-29 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20231028_0205'),
        ('main', '0005_merge_0002_auto_20231027_1159_0004_quoteofday'),
    ]

    operations = [
    ]
