# Generated by Django 4.2.4 on 2023-10-25 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_book_rate'),
    ]

    operations = [
    ]
