# Generated by Django 4.2.6 on 2023-10-26 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20231025_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='rate',
        ),
    ]
