# Generated by Django 4.2.6 on 2023-10-27 03:20

from django.db import migrations
from django.core.management import call_command


def load_my_initial_data(apps, schema_editor):
    call_command("loaddata", "books.json")


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_userprofile_rated_books_userprofile_read_later_books"),
    ]

    operations = [
        migrations.RunPython(load_my_initial_data),
    ]
