# Generated by Django 4.2.4 on 2023-10-27 15:14

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0006_auto_20231025_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nickname', models.TextField(blank=True, null=True)),
                ('phone', models.IntegerField()),
                ('age', models.IntegerField()),
                ('region', models.TextField()),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='rate',
        ),
        migrations.AddField(
            model_name='book',
            name='average_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='user_rated',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
