# Generated by Django 4.2.4 on 2023-10-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_usersearchpreference_delete_searchfeaturestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchFeatureStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UserSearchPreference',
        ),
    ]
