# Generated by Django 4.2.6 on 2023-10-27 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_book_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='average_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='user_rated',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
