# Generated by Django 4.2.4 on 2023-10-28 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20231027_1159'),
        ('main', '0004_quoteofday'),
        ('main', '0007_searchfeaturestatus_delete_usersearchpreference'),
    ]

    operations = [
    ]
