# Generated by Django 4.2.6 on 2023-10-27 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_auto_20231027_1032"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="rate",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="rated_books",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="read_later_books",
        ),
        migrations.AddField(
            model_name="book",
            name="average_rate",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="user_rated",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
        migrations.DeleteModel(
            name="Rate",
        ),
    ]
