# Generated by Django 4.2.4 on 2023-10-28 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_merge_20231029_0032'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuoteOfDay',
        ),
    ]
