# Generated by Django 4.2.4 on 2023-10-28 18:40

from django.db import migrations
from django.core.management import call_command

def load_my_initial_data(apps, schema_editor):
    call_command("loaddata", "main/fixtures/books.json")

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_delete_quoteofday'),
    ]

    operations = [
        migrations.RunPython(load_my_initial_data),
    ]
