# Generated by Django 4.2.4 on 2023-10-29 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_book_favorited_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='favorited_by',
            new_name='favorited',
        ),
    ]
