# Generated by Django 4.2.4 on 2023-10-29 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_rename_favorited_by_book_favorited'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='favorited',
            new_name='favorited_by',
        ),
    ]
