# Generated by Django 4.2.4 on 2023-10-29 07:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0015_rename_favorited_book_favorited_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='favorited_by',
        ),
        migrations.AddField(
            model_name='book',
            name='favorites',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorite_books', to=settings.AUTH_USER_MODEL),
        ),
    ]
