# Generated by Django 4.2.6 on 2023-10-29 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_merge_0002_auto_20231027_1159_0004_quoteofday"),
        ("main", "0017_alter_book_favorites"),
    ]

    operations = []
