# Generated by Django 4.2.4 on 2023-10-29 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_merge_20231029_0356'),
        ('main', '0017_alter_book_favorites'),
    ]

    operations = [
    ]
