# Generated by Django 4.2.6 on 2023-10-29 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0001_initial'),
    ]

    operations = [
    ]
