# Generated by Django 4.2.4 on 2023-10-29 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0002_auto_20231029_1612'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuoteOfDay',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
