# Generated by Django 4.2.6 on 2023-10-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_preview", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Filter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "filter_type",
                    models.CharField(
                        choices=[("terbaru", "Terbaru"), ("random", "Random")],
                        default="terbaru",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
